language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
- OCAML_VERSION=4.06
os: linux
notifications:
  slack:
    secure: JdHVUoxI4Lw5evGKxnrzVIFxE9GBSLiHrF1e9Kavy6ID14aU60+TxCvjy3aqEELMusHYUq+HWey9SIp0BO4Gm07EbAr0K7AaPiFklfAzNMVNVbRtxwngMqSbP76l+Y0VMOmL+TZc5yTr1ZhDK50Q5vdu8CplF4DKg81vr8NS8z0=
